routes/topic.py
from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
)

from models.board import Board
from models.user import User
from routes import (
    current_user,
    new_csrf_token,
    csrf_required,
)

from models.topic import Topic



main = Blueprint('dou_topic', __name__)


@main.route("/")
def index():
    u = current_user()
    print('minn---u', User.all(), u)
    board_id = int(request.args.get('board_id', -1))
    if board_id == -1:
        ms = Topic.all()
    else:
        ms = Topic.all(board_id=board_id)
    # token = new_csrf_token()
    bs = Board.all()
    return render_template("topic/index.html", ms=ms, user=u, bs=bs, bid=board_id)


@main.route('/<int:id>')

def detail(id):
    m = Topic.get(id)
    return render_template("topic/detail.html", topic=m)


@main.route("/new")
def new():
    board_id = int(request.args.get('board_id'))
    bs = Board.all()
    token = new_csrf_token()
    print('bug---token')
    return render_template("topic/new.html", bs=bs, token=token, bid=board_id)



@main.route("/add", methods=["POST"])
@csrf_required
def add():
    u = current_user()
    form = request.form.to_dict()
    t = Topic.add(form, user_id=u.id)
    return redirect(url_for('.detail', id=t.id))

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/style.css">
    <link rel="stylesheet" href="/static/css/index.css">

</head>
<body>
<div class="navbar">
    <div class="navbar-inner">
        <div class="container">
            <!--<ul class="nav pull-left">-->
                <!--<a href="/" class="logo">-->
                    <!--<img src="/static/logo.jpg" width="80px" height="30px">-->
                <!--</a>-->
            <!--</ul>-->
            <ul class='nav pull-right'>
                <li><a href="/">首页</a></li>
                <li><a href="/topic">话题</a></li>
                <li><a href="/profile">个人主页</a></li>
                <li><a href="/mail">私信</a></li>
                <li><a href="/chatroom">聊天室</a></li>
                <li><a href="/setting">设置</a> </li>
                <li><a href="/login/view">登录</a></li>
            </ul>
        </div>
    </div>
</div>

{% block main %}
{% endblock %}
</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>bbs club</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/style.css">
    <link rel="stylesheet" href="/static/css/index.css">

</head>
<body background="/static/imgs/1.jpg"
    style="background-repeat: no-repeat;
           background-size: cover;">
<div class="navbar">
    <div class="navbar-inner">
        <div class="container">
            <!--<ul class="nav pull-left">-->
                <!--<a href="/" class="logo">-->
                    <!--<img src="/static/logo.jpg" width="80px" height="30px">-->
                <!--</a>-->
            <!--</ul>-->
            <ul class='nav pull-right'>
                <li><a href="/">首页</a></li>
                <li><a href="/topic">话题</a></li>
                <li><a href="/profile">个人主页</a></li>
                <li><a href="/mail">私信</a></li>
                <li><a href="/chatroom">聊天室</a></li>
                <li><a href="/setting">设置</a> </li>
                <li><a href="/login/view">登录</a></li>
            </ul>
        </div>
    </div>
</div>
<div>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <h1 style="text-align: center">
        <span style="font-size: 55px;
              color: #ff9955;
              font-family: 华文行楷">
            Welcome~这里有只橘子猪
        </span>
    </h1>
    <br>
    <br>
    <br>
    <br>
    <br>
    <div>
        <h6 style="text-align: center">
            <span style="font-size: 20px;
                  color: #ababab">
                I love three things in this world.
            </span>
            <br>
            <br>
            <span style="font-size: 20px;
                  color: #d0d0d0">
                Sun, moon and you. Sun for morning, moon for night , and you forever .
            </span>
        </h6>
    </div>

</div>
</body>
</html>

templates/login.html
{% extends "base.html" %}
{% block title %}login{% endblock%}
{% block main %}

<div id="content">
  <div class="panel">
    <div class="header">
      <ul class="breadcrumb">
        <li><a href="/">主页</a><span class="divider">/</span></li>
        <li class="active">登录</li>
      </ul>
    </div>
      <div class="inner">
          <form class="form-horizontal" method="post" action="{{ url_for('.register') }}">
            <div class="control-group">
                <label class="control-label">用户名</label>
                <div class="controls">
                    <input type="text" class="input-xlarge" name="username">
                </div>
            </div>
            <div class="control-group">
                <label class="control-label">密码</label>
                <div class="controls">
                    <input type="text" class="input-xlarge" name="password">
                </div>
            </div>
            <div class="form-actions">
                <input type="submit" class="span-primary" value="注册">
            </div>
        </form>
          <form class="form-horizontal" method="post" action="{{ url_for('.login') }}">
        <div class="control-group">
            <label class="control-label">用户名</label>
            <div class="controls">
                <input type="text" class="input-xlarge" name="username">
            </div>
        </div>
        <div class="control-group">
            <label class="control-label">密码</label>
            <div class="controls">
                <input type="text" class="input-xlarge" name="password">
            </div>
        </div>
        <div class="form-actions">
          <input class="span-primary" value="登录" type="submit">
        </div>
    </form>
      </div>
{% endblock %}

templates/profile.html
{% extends "base.html" %}
{% block title %}profile{% endblock%}
{% block main %}

<div id="main">

    <div id="content">
        <div class="panel">
            <div class="header">
                <ul class="breadcrumb">
                    <li><a href="/topic/">主页</a><span class="divider">/</span></li>
                </ul>
            </div>
            <div class="inner userinfo">
                <div class="user_big_avatar">
                    <img src="{{ user.image }}">
                </div>
                <a class="dark">{{ user.username }}</a>
                <p class="col_fade">注册时间 {{ user.created_time | format_time }}</p>
            </div>
        </div>

        <div class="panel">
            <div class="header">
                <span class="col_fade">最近创建的话题</span>
            </div>
            <div class="cell">
                <div class="topic_list">
                    {% for t in ms_created %}
                    <div class="cell">
                        <a class="user_avatar pull-left">
                            <img src="{{ t.user().image }}"/>
                        </a>
                        <div class="topic_title_wrapper">
                            <span>{{ t.replies() | count }} / {{ t.views }}</span>
                            {# count(t.replies()) #}
                            {# <span>{{ t.reply_count() }} / {{ t.views }}</span> #}
                            <a class="topic_title" href="{{ url_for('dou_topic.detail', id=t.id) }}">
                                {{ t.title }}
                            </a>
                            <a class="last_time pull-right">
                                <img class="user_small_avatar"
                                     src="{{ t.last_reply().user().image }}">
                                <span class="last_active_time">{{ t.last_reply().created_time | format_time }}</span>
                            </a>
                        </div>

                    </div>
                    {% endfor %}
                </div>
            </div>

            <div class="panel">
                <div class="header">
                    <span class="col_fade">最近参与的话题</span>
                </div>

                <div class="cell">
                    <div class="topic_list">
                        {% for t in ms_recented %}
                        <div class="cell">
                            <a class="user_avatar pull-left">
                                <img src="{{ t.user().image }}"/>
                            </a>
                            <div class="topic_title_wrapper">
                                <span>{{ t.replies() | count }} / {{ t.views }}</span>
                                {# count(t.replies()) #}
                                {# <span>{{ t.reply_count() }} / {{ t.views }}</span> #}
                                <a class="topic_title" href="{{ url_for('dou_topic.detail', id=t.id) }}">
                                    {{ t.title }}
                                </a>
                                <a class="last_time pull-right">
                                    <img class="user_small_avatar"
                                         src="{{ t.last_reply().user().image }}">
                                    <span class="last_active_time">{{ t.last_reply().created_time | format_time }}</span>
                                </a>
                            </div>
                        </div>
                        {% endfor %}
                    </div>

                </div>

                {% endblock %}

templates/setting.html
{% extends "base.html" %}
{% block title %}setting{% endblock%}
{% block main %}

<div id="main">
    <div id="sidebar">
        <div class='panel'>
            <div class='header'>
                <span class='col_fade'>个人信息</span>
            </div>
            <div class='inner'>
                <div class='user_card'>
                    <div>
                        <a class='user_avatar' href="/profile">
                            <img src="{{ user.image }}"/>
                        </a>
                        <span class='user_name'><a class='dark' href="/profile">{{ user.username }}</a></span>
                        <div class="space clearfix"></div>
                        <span class="signature">
                            “
                                {{ user.signature }}

                            ”
                        </span>
                    </div>
                </div>
            </div>
        </div>
        <div class="panel">
            <div class="inner">
                <a href="{{ url_for('dou_topic.new') }}" class="create_topic_btn">
                    <span class="span-success">发布话题xxxxxxxxxxxxxxxx</span>
                </a>
            </div>
        </div>
    </div>
    <div id='content'>
        <div class='panel'>
            <div class='header'>
                <ul class='breadcrumb'>
                    <li><a href='/'>主页</a><span class='divider'>/</span></li>
                    <li class='active'>设置</li>
                </ul>
            </div>
            <div class='inner'>
                <form id='setting_form' class='form-horizontal' action='/setting/edit' method='post'>
                    <div class='control-group'>
                        <label class='control-label' for='name'>用户名</label>
                    </div>
                    <div class='controls'>
                        <input class='input-xlarge' id='username' name='username' size='30' type='text'
                               value="{{ user.username }}"/>
                    </div>
                    <br>
                    <div class='control-group'>
                        <label class='control-label' for='signature'>个性签名</label>

                        <div class='controls'>
                            <textarea class='input-xlarge' id='signature' name='signature' size='30'></textarea>
                        </div>
                    </div>
                    <!--<input type='hidden' id='action' name='action' value='change_setting'/>-->
                    <!--<input type='hidden' name='_csrf' value='GWgElEnr-qin-5-hidkvBFQqLNKO9T21GzrU'/>-->

                    <div class='form-actions'>
                        <input type='submit' class='span-primary submit_btn' data-loading-text="保 存中.." value='保存设置'/>
                    </div>
                </form>


                <div class='panel'>
                    <div class='header'>
                        <span class='col_fade'>更改密码</span>
                    </div>
                    <div class='inner'>
                        <form id='change_pass_form' class='form-horizontal' action='/setting/editpwd' method='post'>
                            <div class='control-group'>
                                <label class='control-label' for='old_pass'>当前密码</label>

                                <div class='controls'>
                                    <input class='input-xlarge' type='password' id='old_pass' name='old_pass'
                                           size='30'/>
                                </div>
                            </div>
                            <div class='control-group'>
                                <label class='control-label' for='new_pass'>新密码</label>

                                <div class='controls'>
                                    <input class='input-xlarge' type='password' id='new_pass' name='new_pass'
                                           size='30'/>
                                </div>
                            </div>
                            <!--<input type='hidden' id='action' name='action' value='change_password'/>-->
                            <!--<input type='hidden' name='_csrf' value='GWgElEnr-qin-5-hidkvBFQqLNKO9T21GzrU'/>-->

                            <div class='form-actions'>
                                <input type='submit' class='span-primary submit_btn' data-loading-text="更改中.."
                                       value='更改密码'/>
                            </div>
                        </form>
                        <form method="post"
                              action="{{ url_for('.avatar_add')}}"
                              enctype="multipart/form-data"
                        >
                            <input type="file" name="avatar">
                            <button type="submit">上传头像</button>
                        </form>

                        <!--<img src="{{ user.image }} ">-->
                    </div>
                </div>
            </div>
        </div>
        {% endblock %}