models/topic.py
from sqlalchemy import Integer, Column, UnicodeText, Unicode

from models.base_model import SQLMixin, db
from models.user import User
from models.reply import Reply


class Topic(SQLMixin, db.Model):
    views = Column(Integer, nullable=False, default=0)
    title = Column(Unicode(50), nullable=False)
    content = Column(UnicodeText, nullable=False)
    user_id = Column(Integer, nullable=False)
    board_id = Column(Integer, nullable=False)

    @classmethod
    def add(cls, form, user_id):
        form['user_id'] = user_id
        m = super().new(form)
        return m

    @classmethod
    def get(cls, id):
        m = cls.one(id=id)
        m.views += 1
        m.save()
        return m

    def user(self):
        u = User.one(id=self.user_id)
        return u

    def replies(self):
        ms = Reply.all(topic_id=self.id)
        return ms

    def reply_count(self):
        count = len(self.replies())
        return count

    def last_reply(self):
        if self.reply_count() == 0:
            return self
        else:
            return self.replies()[-1]

routes/reply.py
from flask import (
    request,
    redirect,
    url_for,
    Blueprint,
)

from routes import current_user

from models.reply import Reply


main = Blueprint('dou_reply', __name__)


@main.route("/add", methods=["POST"])
def add():
    form = request.form.to_dict()
    u = current_user()
    print('DEBUG', form)
    m = Reply.add(form, user_id=u.id)
    return redirect(url_for('dou_topic.detail', id=m.topic_id))

routes/topic.py
from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
)

from models.board import Board
from models.user import User
from routes import (
    current_user,
    new_csrf_token,
    csrf_required,
)

from models.topic import Topic



main = Blueprint('dou_topic', __name__)


@main.route("/")
def index():
    u = current_user()
    print('minn---u', User.all(), u)
    board_id = int(request.args.get('board_id', -1))
    if board_id == -1:
        ms = Topic.all()
    else:
        ms = Topic.all(board_id=board_id)
    # token = new_csrf_token()
    bs = Board.all()
    return render_template("topic/index.html", ms=ms, user=u, bs=bs, bid=board_id)


@main.route('/<int:id>')

def detail(id):
    m = Topic.get(id)
    return render_template("topic/detail.html", topic=m)


@main.route("/new")
def new():
    board_id = int(request.args.get('board_id'))
    bs = Board.all()
    token = new_csrf_token()
    print('bug---token')
    return render_template("topic/new.html", bs=bs, token=token, bid=board_id)



@main.route("/add", methods=["POST"])
@csrf_required
def add():
    u = current_user()
    form = request.form.to_dict()
    t = Topic.add(form, user_id=u.id)
    return redirect(url_for('.detail', id=t.id))

templates/topic/detail.html
<!--templates/topic/detail.html-->

{% extends "base.html" %}
{% block title %}detail topic{% endblock%}
{% block main %}
<div id="main">
    <div id="content">
        <div class='panel'>
            <div class='header topic_header'>
        <span class="topic_full_title">
			{{ topic.title }}
      	</span>
                <div class="changes">
            <span>
                发布于 {{ topic.created_time | format_time }}
            </span>
                    <span >
                作者 <a href="/user/{{ topic.user().username }}">{{ topic.user().username }}</a>
                {# 作者 {{ User.one(id=topic.user_id).username }} #}
        	</span>
                    <span>
          	    {{ topic.views }} 次浏览
        	</span>
                    <span>
                来自 问答
            </span>
                </div>
            </div>

            <div class='inner topic'>
                <div class='topic_content'>
                    <div class="markdown-text">{{ topic.content }}</div>
                </div>
            </div>
        </div>
    </div>

    <div class='panel'>
        <div class='header'>
            <span class='col_fade'>
                <!-- 过滤器 -->
                {{ topic.replies() | count }} 回复
            </span>
        </div>
        {% for r in topic.replies() %}
        {% set u = r.user() %}
        <div class='cell reply_area reply_item'>
            <div class='user_info'>
                <a class='dark reply_author'>
                    {{ u.username }}
                </a>
                <a class="reply_time">
                    {{ loop.index }}楼 / {{ loop.length }}楼 •
                    <span class="gua-time" data-created_time="{{ r.created_time }}"></span>
                </a>
            </div>
            <div class='user_action'>
                    <span>
                        <i class="fa up_btn
                          fa-thumbs-o-up
                          invisible" title="喜欢"></i>
                        <span class="up-count">
                        </span>
                    </span>
            </div>
            <div class='reply_content from-leiwei1991'>
                <div class="markdown-text">{{ r.content }}</div>
            </div>
        </div>
        {% endfor %}
    </div>
    <div>
        <form action="{{ url_for('dou_reply.add') }}" method="post">
            <input type="hidden" name="topic_id" value="{{ topic.id }}">
            <textarea name="content"></textarea>
            <button>添加回复</button>
        </form>
    </div>
</div>
<script src="https://cdn.bootcss.com/marked/0.3.19/marked.min.js"></script>
<script src="https://cdn.bootcss.com/prism/1.13.0/prism.js"></script>
<script src="https://cdn.bootcss.com/prism/1.13.0/plugins/autoloader/prism-autoloader.min.js"></script>
<script>
    var e = function (sel) {
        return document.querySelector(sel)
    }

    var es = function (sel) {
        return document.querySelectorAll(sel)
    }

    var markContents = function () {
        // markdown -> html 的处理放在高亮前面
        // 因为高亮是针对 html 格式的
        // lang -> language 不需要转 prism 自动转了
        var contentDivs = es('.markdown-text')
        for (var i = 0; i < contentDivs.length; i++) {
            var contentDiv = contentDivs[i]
            console.log('pre marked', contentDiv.textContent, contentDiv.innerHTML)
            var content = marked(contentDiv.textContent)
            console.log('after marked', content)
            contentDiv.innerHTML = content
        }
    }

    var highlight = function() {
         // 自动加载对应的语言 不然要手动加入各个语言的 js
        Prism.plugins.autoloader.languages_path = 'https://cdn.bootcss.com/prism/1.13.0/components/'
    }

    var registerTimer = function () {
        setInterval(function () {
            var times = es('.gua-time')
            for (var i = 0; i < times.length; i++) {
                var t = times[i]
                var time = Number(t.dataset.created_time)
                var now = Math.floor(new Date() / 1000)
                var delta = now - time
                var s = `${delta} 秒前`
                t.innerText = s
            }
        }, 1000)
    }

    var __main = function () {
        markContents()
        highlight()
        registerTimer()
    }

    __main()


</script>
{% endblock %}

templates/topic/index.html
{% extends "base.html" %}
{% block title %}topic{% endblock%}
{% block main %}

<div id="main">
    <div id="sidebar">
        <div class='panel'>
            <div class='header'>
                <span class='col_fade'>个人信息</span>
            </div>
            <div class='inner'>
                <div class='user_card'>
                    <div>
                        <a class='user_avatar' href="/profile">
                            <img src="{{ user.image }}"/>
                        </a>
                        <span class='user_name'>
                            <a class='dark' href="/profile">{{ user.username }}</a>
                        </span>
                        <div class="space clearfix"></div>
                        <span class="signature">
                            “
                                {{ user.signature }}

                            ”
                        </span>
                    </div>
                </div>
            </div>
        </div>

        <div class="panel">
            <div class="inner">
                <a href="/topic/new?board_id={{ bid }}" class="create_topic_btn">
                    <span class="span-success">发布话题xxxxxxxxxxxxxxxx</span>
                </a>
            </div>
        </div>
    </div>
    <div id="content">
        <div class="panel">
            <div class="header">
                <a href="/topic"
                   class="topic-tab current-tab">
                    全部的帖子
                </a>

                {% for b in bs %}
                <a href="/topic?board_id={{ b.id }}"
                   class="topic-tab current-tab">
                    {{ b.title }}
                </a>
                {% endfor %}
            </div>
            <div class="inner post">
                <div class="topic_list">
                    {% for t in ms %}
                    <div class="cell">
                        <a class='user_avatar pull-left'>
                            <img src="{{ t.user().image }}"/>
                        </a>
                        <div class="topic_title_wrapper">
                            <a class="topic_title" href="{{ url_for('dou_topic.detail', id=t.id) }}">
                                {{ t.title }}
                            </a>
                            <span>{{ t.replies() | count }} / {{ t.views }}</span>
                            {# count(t.replies()) #}
                            {# <span>{{ t.reply_count() }} / {{ t.views }}</span> #}

                            <a class="last_time pull-right">
                                <img class="user_small_avatar"
                                     src="{{ t.last_reply().user().image }}">
                                <span class="last_active_time">{{ t.last_reply().created_time | format_time }}</span>
                            </a>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/topic/new.html
{% extends "base.html" %}
{% block title %}new topic{% endblock%}
{% block main %}

<div id="main">
    <div id="content">
        <div class="panel">
            <div class="inner post">
                <form id="create_topic_form" method="post" action="{{ url_for('.add', token=token) }}">
                    <fieldset>
        <textarea autofocus class='span9' id='title'
                  name='title' rows='1'
                  placeholder="标题字数 10 字以上"></textarea>
                        <span class="tab-selector">选择版块：</span>
                        <select name="board_id" id="board" required>
                            {% for b in bs %}
                            {% if bid == b.id %}
                            <option value="{{ b.id }}" selected>{{ b.title }}</option>
                            {% else %}
                            <option value="{{ b.id }}">{{ b.title }}</option>
                            {% endif %}
                            {% endfor %}
                        </select>
                        <div class='markdown_editor in_editor'>
                            <div class='markdown_in_editor'>
                                <textarea class='editor' name='content' rows='20'
                                          placeholder='文章支持 Markdown 语法, 请注意标记代码'></textarea>
                                <div class='editor_buttons'>
                                    <input type="submit" class='span-primary submit_btn' data-loading-text="提交中"
                                           value="提交">
                                </div>
                            </div>
                        </div>
                    </fieldset>
                </form>
            </div>
        </div>
    </div>
</div>
<script>
  (function () {
    var editor = new Editor();
    editor.render($('.editor')[0]);
  })();


</script>
{% endblock %}